
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/Home/Navbar";
import Footer from "@/components/Home/Footer";
import CartProvider from "@/components/cart/cartProvider";
import CheckoutProvider from "@/components/cart/CheckoutProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Furniro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <CheckoutProvider>
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
          </CheckoutProvider>
        </CartProvider>
      </body>
    </html>
  );
}
